function R_b = myR_b(phi,theta,psi)
%MYR_B
%    R_B = MYR_B(M_B,M_1,M_2,IXX,IYY,IZZ,IX1,IY1,IZ1,IX2,IY2,IZ2,L1,L2,X,Y,Z,PHI,THETA,PSI,N1,N2,X_DOT,Y_DOT,Z_DOT,PHI_DOT,THETA_DOT,PSI_DOT,N1_DOT,N2_DOT)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    01-May-2018 19:06:06

t2 = cos(psi);
t3 = sin(phi);
t4 = sin(psi);
t5 = cos(phi);
t6 = sin(theta);
t7 = cos(theta);
R_b = reshape([t2.*t7,t4.*t7,-t6,-t4.*t5+t2.*t3.*t6,t2.*t5+t3.*t4.*t6,t3.*t7,t3.*t4+t2.*t5.*t6,-t2.*t3+t4.*t5.*t6,t5.*t7],[3,3]);
